name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: 'Breaking'
    labels:
      - 'change: breaking'
  - title: 'New'
    labels:
      - 'change: feature'
      - 'change: enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'change: bug-fix'
  - title: 'Maintenance'
    label: 'change: chore'
  - title: 'Documentation'
    label: 'change: docs'
  - title: 'Dependency Updates'
    label: 'change: dependencies'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'change: breaking'
  minor:
    labels:
      - 'change: enhancement'
      - 'change: feature'
  patch:
    labels:
      - 'change: bug'
      - 'change: chore'
      - 'change: dependencies'
      - 'change: docs'
      - 'change: patch'

  default: patch

  exclude-labels:
    - 'change: skip-changelog'

template: |
  ## What's Changed
  $CHANGES
  ## Contributors
  $CONTRIBUTORS
